"""Refactor Menu and SubMenu for production

Revision ID: 23a470ce9123
Revises: 04f61633530b
Create Date: 2026-07-17 16:25:46.974512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a470ce9123'
down_revision: Union[str, Sequence[str], None] = '04f61633530b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('menu', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('menu', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('menu', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_menu_order_index'), 'menu', ['order_index'], unique=False)
    op.create_unique_constraint(None, 'menu', ['title'])
    op.create_unique_constraint(None, 'menu', ['path'])
    op.add_column('submenu', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('submenu', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('submenu', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_submenu_order_index'), 'submenu', ['order_index'], unique=False)
    op.create_unique_constraint('uq_submenu_path_per_menu', 'submenu', ['menu_id', 'path'])
    op.create_unique_constraint('uq_submenu_title_per_menu', 'submenu', ['menu_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_submenu_title_per_menu', 'submenu', type_='unique')
    op.drop_constraint('uq_submenu_path_per_menu', 'submenu', type_='unique')
    op.drop_index(op.f('ix_submenu_order_index'), table_name='submenu')
    op.drop_column('submenu', 'updated_at')
    op.drop_column('submenu', 'created_at')
    op.drop_column('submenu', 'is_deleted')
    op.drop_constraint(None, 'menu', type_='unique')
    op.drop_constraint(None, 'menu', type_='unique')
    op.drop_index(op.f('ix_menu_order_index'), table_name='menu')
    op.drop_column('menu', 'updated_at')
    op.drop_column('menu', 'created_at')
    op.drop_column('menu', 'is_deleted')
    op.drop_column('menu', 'order_index')
    # ### end Alembic commands ###
