"""rename route to path

Revision ID: 3fa4f7cae637
Revises: 
Create Date: 2026-07-10 13:22:52.655023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa4f7cae637'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('path', sa.String(length=100), nullable=True))
    op.drop_column('menu', 'route')
    op.add_column('submenus', sa.Column('path', sa.String(), nullable=True))
    op.drop_column('submenus', 'route')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenus', sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('submenus', 'path')
    op.add_column('menu', sa.Column('route', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('menu', 'path')
    # ### end Alembic commands ###
