"""add otp fields to user

Revision ID: 6b7adf477274
Revises: 0c9a13249be8
Create Date: 2026-06-27 01:05:02.037261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7adf477274'
down_revision: Union[str, Sequence[str], None] = '0c9a13249be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_verified')
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
