"""init_db

Revision ID: 6be7341a8325
Revises: 
Create Date: 2026-06-20 18:30:05.833370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be7341a8325'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_erv_logs_id'), table_name='erv_logs')
    op.drop_table('erv_logs')
    op.drop_column('add_students', 'dob')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'])
    op.drop_constraint(op.f('unique_batch_per_course'), 'faculty_batches', type_='unique')
    op.create_foreign_key(None, 'lectures', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'tests', 'courses', ['course_id'], ['id'])
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'lectures', type_='foreignkey')
    op.create_unique_constraint(op.f('unique_batch_per_course'), 'faculty_batches', ['name', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.add_column('add_students', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('erv_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shift', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pump_101a_prev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pump_101a_current', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pump_101a_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('line_fill_batch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_fill_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shutdown_pr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shutdown_cur', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shutdown_tot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('power_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('power_month', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('power_year', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('erv_logs_pkey'))
    )
    op.create_index(op.f('ix_erv_logs_id'), 'erv_logs', ['id'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_assignments_pkey'))
    )
    # ### end Alembic commands ###
