"""add gender student id employee id

Revision ID: 92f1c9858ecb
Revises: e7a1b6d04a30
Create Date: 2026-09-16 22:20:18.149035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f1c9858ecb'
down_revision: Union[str, Sequence[str], None] = 'e7a1b6d04a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_details_student_id_key'), 'student_details', type_='unique')
    op.create_index(op.f('ix_student_details_student_id'), 'student_details', ['student_id'], unique=True)
    op.drop_constraint(op.f('teacher_details_employee_id_key'), 'teacher_details', type_='unique')
    op.create_index(op.f('ix_teacher_details_employee_id'), 'teacher_details', ['employee_id'], unique=True)
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_index(op.f('ix_teacher_details_employee_id'), table_name='teacher_details')
    op.create_unique_constraint(op.f('teacher_details_employee_id_key'), 'teacher_details', ['employee_id'])
    op.drop_index(op.f('ix_student_details_student_id'), table_name='student_details')
    op.create_unique_constraint(op.f('student_details_student_id_key'), 'student_details', ['student_id'])
    # ### end Alembic commands ###
