"""create sidebar table

Revision ID: c232fc183611
Revises: 6843fdc814b2
Create Date: 2026-06-25 19:54:33.160314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c232fc183611'
down_revision: Union[str, Sequence[str], None] = '6843fdc814b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sidebar_id'), table_name='sidebar')
    op.drop_table('sidebar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidebar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('route', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sidebar_pkey'))
    )
    op.create_index(op.f('ix_sidebar_id'), 'sidebar', ['id'], unique=False)
    # ### end Alembic commands ###
