from .user import User
from .role import Role
from .menu import Menu
from .submenu import SubMenu
from .permission import Permission
from .role_menu import RoleMenu
from .role_submenu import RoleSubMenu
from .role_permission import RolePermission
from .userManagement.student import StudentDetail
from .userManagement.teacher import TeacherDetail
from .userManagement.parent import ParentDetail
