"""standardize_model_names

Revision ID: 04f61633530b
Revises: 3fa4f7cae637
Create Date: 2026-07-17 14:35:09.578698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f61633530b'
down_revision: Union[str, Sequence[str], None] = '3fa4f7cae637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Drop the empty `submenu` table that FastAPI auto-created
    op.drop_table('submenu')

    # 2. Rename the old tables to preserve your data
    op.rename_table('RolePermission', 'role_permission')
    op.rename_table('RoleSubMenu', 'role_submenu')
    op.rename_table('submenus', 'submenu')

    # 3. Rename the primary key column in the submenu table
    op.alter_column('submenu', 'submenu_id', new_column_name='id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submenu', 'id', new_column_name='submenu_id')
    op.rename_table('submenu', 'submenus')
    op.rename_table('role_submenu', 'RoleSubMenu')
    op.rename_table('role_permission', 'RolePermission')
    # ### end Alembic commands ###
